# Workflow (No indentation required for naming the workflow)

name: Hello
# On tells when the workflow should run (Give indentation by tab)
on: 
  workflow_dispatch: 
# job tells what the workflow should do, there can be more than one jobs, hence we write jobs
# job is an object so need indentation
jobs:
# first job (give indentation)
  say-hello:
  # creates an ephemeral container with ubuntu running. Below jobs will run and expire.
    runs-on: ubuntu-latest
    # That ephemeral container will have steps to execute, hence name those steps and use run: run has the command
    steps:
      - name: Say Hello to everyone
        run: echo "Hello Dosto"

